version: "3.1"

services:

  angular:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 4200:4200

  spring:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 8082:8082
      - 8001:8001
    depends_on:
      - db
      - kafka

  db:
    build:
      context: ./dockerfile/hsqldb
      dockerfile: Dockerfile
    ports:
      - 9001:9001

  zookeeper:
    build:
      context: ./dockerfile/zookeeper
      dockerfile: Dockerfile
    ports:
      - 2181:2181

  kafka:
    build:
      context: ./dockerfile/kafka
      dockerfile: Dockerfile
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    hostname: kafka
    links:
      - zookeeper

  init:
    build:
      context: dockerfile/init
      dockerfile: Dockerfile


volumes:
  db-data: